/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ApiPublicAppointmentsRouteImport } from './routes/api/public/appointments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppointmentsRoute = ApiPublicAppointmentsRouteImport.update({
  id: '/api/public/appointments',
  path: '/api/public/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients': typeof PatientsRoute
  '/services': typeof ServicesRoute
  '/api/public/appointments': typeof ApiPublicAppointmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients': typeof PatientsRoute
  '/services': typeof ServicesRoute
  '/api/public/appointments': typeof ApiPublicAppointmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients': typeof PatientsRoute
  '/services': typeof ServicesRoute
  '/api/public/appointments': typeof ApiPublicAppointmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patients' | '/services' | '/api/public/appointments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patients' | '/services' | '/api/public/appointments'
  id: '__root__' | '/' | '/patients' | '/services' | '/api/public/appointments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsRoute: typeof PatientsRoute
  ServicesRoute: typeof ServicesRoute
  ApiPublicAppointmentsRoute: typeof ApiPublicAppointmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointments': {
      id: '/api/public/appointments'
      path: '/api/public/appointments'
      fullPath: '/api/public/appointments'
      preLoaderRoute: typeof ApiPublicAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsRoute: PatientsRoute,
  ServicesRoute: ServicesRoute,
  ApiPublicAppointmentsRoute: ApiPublicAppointmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
